import {MantineProvider} from "@mantine/core";
import Wrapper from '@/components/Wrapper'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wrapper>
            {children}
        </Wrapper>
      </body>
    </html>
  )
}
